services:
  gitlab_web:
    image: gitlab/gitlab-ee:latest
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
    networks:
      - gitlab_network

  gitlab_runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    volumes:
      - "./runner:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - gitlab_network

networks:
  gitlab_network:
    name: gitlab_network
